### ISSUE TITLE
Sass Lint Sample Config Not Default

### ISSUE THREAD

**Issue by Snugug** [skovhus/SublimeLinter-contrib-sass-lint#1]
You like to the Sample Config File as the defaults for Sass Lint. That is just a sample file to let users understand what a config file with lots of options may look like, but are not the defaults. The defaults can be found in our [lib/config file](https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml)

**Comment by skovhus** [comment]
Thanks. It should be fixed now.
