### ISSUE TITLE
can't use with webpack syntax

### ISSUE THREAD

**Issue by mqklin** [skovhus/SublimeLinter-contrib-sass-lint#10]
It gives an error when I try to use it with `css-loader`:

```
  :local(.styles) {
    $root: &; // => Please check validity of the block starting from this line (Fatal)
   ...
```

How can I fix it?

**Comment by skovhus** [comment]
Hi @mqklin,

AFAIK this is not valid sass/scss syntax, so the `sass-lint` cannot parse/lint it. But please create an issue here https://github.com/sasstools/sass-lint to verify that. This repo is for the SublimeLinter integration. :)

**Comment by mqklin** [comment]
Ok. I've created: https://github.com/sasstools/sass-lint/issues/576

**Comment by skovhus** [comment]
:+1:
