### ISSUE TITLE
sass-lint doesn't work with tabs?

### ISSUE THREAD

**Issue by theskillwithin** [skovhus/SublimeLinter-contrib-sass-lint#17]
does not work with tabs in sass syntax...... thanks sass-lint.

is there a way to fix this sass-lint problem in sublimelinter?

2:2   warning  Mixed tabs and spaces                                                        indentation

**Comment by skovhus** [comment]
Please submit this issue to sass-lint repo. This linter is a simple wrapper, so we cannot fix the underlying tool. 

Thanks. : )
