### ISSUE TITLE
not support embedded *.vue sass

### ISSUE THREAD

**Issue by lessmind** [skovhus/SublimeLinter-contrib-sass-lint#19]
Hi
This plugin doesn't support embedded `*.vue` sass.

I'm trying to make some changes to make it work
https://github.com/outlandinc/SublimeLinter-contrib-sass-lint/commit/7cc689519d4788d6211984fb732c59c842505b8c

I did manage to get the linter process embedded code, but seems that the `<style lang="sass"></style>` part are also included in the code piece, and results in `sass-lint` error

![image](https://user-images.githubusercontent.com/905459/34560324-458d5446-f180-11e7-9e0f-a99261992cbb.png)
![image](https://user-images.githubusercontent.com/905459/34560352-555cdda6-f180-11e7-862f-c9464c39f7d4.png)

Would you please help so I could make this PR work? Thanks.

**Comment by skovhus** [comment]
Hi @lessmind 

Thanks for contributing here. As I'm not really using this plugin more I not of much help here... Except for releasing a new version with your fix. 

Hopefully by opening this issue you might find someone that are able to help you get this PR finished.

**Comment by lessmind** [comment]
Sure, thanks!

**Comment by lessmind** [comment]
https://github.com/skovhus/SublimeLinter-contrib-sass-lint/pull/20

**Comment by lessmind** [comment]
I figured it out 🎉 
PR created! I'm totally new to python, let me know if anything wrong.
Thanks.

**Comment by skovhus** [comment]
Thanks you so much for this, and sorry for the slow response time. Version 1.1.0 should soon be available. @lessmind can you check that it works?

https://packagecontrol.io/packages/SublimeLinter-contrib-sass-lint
