### ISSUE TITLE
Local config file is ignored

### ISSUE THREAD

**Issue by Doodidan** [skovhus/SublimeLinter-contrib-sass-lint#25]
This linter ignore local config file. `sass-lint` console command don't in the same time.
Folder structure:
- project
- - .sass-lint.yml
- - sources
- - - css
- - - - style.css

On the screenshot: a lot of warnings, example of warning in top
![image](https://user-images.githubusercontent.com/8870929/37650870-5883661a-2c47-11e8-9eb5-c521f176d1c8.png)

On this screenshot: few warnings in different lines
![image](https://user-images.githubusercontent.com/8870929/37650989-b16888fa-2c47-11e8-8172-444a68dbe37a.png)

**Comment by skovhus** [comment]
@GoshaEgorian thanks for reporting this. As I'm not really using Sublime anymore, I would like help looking into this issue. PRs are more than welcome. : )

**Comment by zed0** [comment]
We've just had this issue.
Without editing the source you can fix this using your local configuration by adding the following to your SublimeLinter preferences (Preferences -> Package Settings -> SublimeLinter -> Settings)
```
// SublimeLinter Settings - User
{
    "linters": {
        "sass": {
            "working_dir": "${file_path}"
        }
    }
}
```

**Comment by Shelagh-Lewins** [comment]
Thank you @zed0! I was tearing my hair out trying to get sass-lint to accept tab indentation in Sublime Text 3.

Here is a little more detail about my setup in case it helps anybody else.

In SublimeLinter preferences (Preferences -> Package Settings -> SublimeLinter -> Settings):

```
    "linters": {
        "sass": {
            "working_dir": "${/home/myusername}"
        }
    },
```

And then I added a file .sasslintrc to my Home folder:

```
{
  "rules": {
    "indentation": [
      1,
      {
        "size": "tab"
      }
    ]
  }
}
```

**Comment by rgpublic** [comment]
Wow. Took my ages to finally find this. Thanks a lot @Shelagh-Lewins !
You can simplify this even more on most systems to:

```
    "linters": {
        "sass": {
            "working_dir": "~"
        }
    }
```

**Comment by rgpublic** [comment]
Well, but in the README file it says:
>  If a `.sass-lint.yml` file is not found in the file hierarchy starting with the linted file, your home directory will also be searched.

IMHO, it *should* work like that, i.e. it should search in the user's home directory *by default* without configuring *anything*.
But it doesn't. Don't know whether anyone else thinks it should search there by default. But if it doesn't, at the very least this confusing sentence should be removed.
