### ISSUE TITLE
Home directory config file ignored

### ISSUE THREAD

**Issue by nuuou** [skovhus/SublimeLinter-contrib-sass-lint#26]
I'm running into a bit of an issue where it doesn't appear my home directory `.sass-lint.yml` file is being respected. I don't have a local `.sass-lint.yml` in my project, only the one in my home directory.

SASS-Lint is working, but looks to be falling-back to "default" config (instead of my specified config).

Is there any additional settings I need to add to by SublimeLinter User settings?

I'm running the newest version of this plugin, as published to the Sublime Package Control.

A bit of additional info:
- **OS**: macOS 10.13.2
- **Sublime Version**: 3159 (dev)

**Comment by skovhus** [comment]
Thanks for reporting this. I’m not really using `sass-lint` or Sublime anymore. 

But feel free to submit a PR, then I will have a look.

**Comment by skovhus** [comment]
Is this related to https://github.com/skovhus/SublimeLinter-contrib-sass-lint/issues/8 ?

**Comment by nuuou** [comment]
Honestly not entirely sure. I _think_ my paths were setup correctly but I was still running into this.
In any case, I've moved on to using [SublimeLinter-contrib-stylelint](https://github.com/kungfusheep/SublimeLinter-contrib-stylelint), so this is no longer an issue for me.
