### ISSUE TITLE
Sublime SASS config settings

### ISSUE THREAD

**Issue by KoltonG** [skovhus/SublimeLinter-contrib-sass-lint#3]
Hey, I was just curious on where I can find what I can turn on/off for this linter and where do I place it in the SublimeLinter.sublime-settings file. I am presently looking to change the indentation lint rule and cannot determine where to place it.

I was thinking in the excludes array, but I don't have any reference of what to write or where to find it.

``` json
"sass": {
                "@disable": false,
                "args": [],
                "excludes": [
                    "indentation"
                ],
            }
```

**Comment by skovhus** [comment]
See https://github.com/skovhus/SublimeLinter-contrib-sass-lint#settings ... You just need a `.sass-lint.yml` file in your project root. See https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml#L57
