### ISSUE TITLE
Please check validity of block

### ISSUE THREAD

**Issue by asaadmahmood** [skovhus/SublimeLinter-contrib-sass-lint#9]
Not sure why sublime is giving warnings in these places.

![screen shot 2016-03-16 at 3 46 22 pm](https://cloud.githubusercontent.com/assets/11034289/13809793/4286bb42-eb8e-11e5-8a1b-948e9e86fc07.png)

![screen shot 2016-03-16 at 3 44 00 pm](https://cloud.githubusercontent.com/assets/11034289/13809774/21e68cdc-eb8e-11e5-82be-3cf6b7dc8b01.png)

**Comment by skovhus** [comment]
Hi @asaadmahmoodspin 

Thanks for reporting this. It seems to be an issue with the parser/AST that `sass-lint` is using. Please create an issue at https://github.com/sasstools/sass-lint

I can also recommend trying out https://github.com/attenzione/SublimeLinter-scss-lint , which uses the more mature but Ruby dependent `scss-lint`.

Thanks
